disp('***********************************************************************');
disp('* Flexible Energy Scheduling Tool for Integrating Variable generation *');
disp('***********************************************************************');
disp('**   FFFFFF    EEEEEE    SSSSSS    TTTTTTTT    IIIIII    VV     VV   **');
disp('**   FF        EE        SS           TT         II       VV   VV    **');
disp('**   FFFFFF    EEEEEE    SSSSSS       TT         II        VV VV     **');
disp('**   FF        EE            SS       TT         II         VVV      **');
disp('**   FF        EEEEEE    SSSSSS       TT       IIIIII        V       **');
disp('***********************************************************************');
disp('**************** National Renewable  Energy Laboratory ****************');
disp('***********************************************************************');
disp(' ');