%data size
size_DAC_LOAD_FULL = size(DAC_LOAD_FULL,1);
size_RTC_LOAD_FULL = size(RTC_LOAD_FULL,1);
size_RTD_LOAD_FULL = size(RTD_LOAD_FULL,1);
size_ACTUAL_LOAD_FULL = size(ACTUAL_LOAD_FULL,1);

size_ACTUAL_LOAD_FULL = size(ACTUAL_LOAD_FULL,1);

%data size
size_DAC_VG_FULL = size(DAC_VG_FULL,1);
size_RTC_VG_FULL = size(RTC_VG_FULL,1);
size_RTD_VG_FULL = size(RTD_VG_FULL,1);
size_ACTUAL_VG_FULL = size(ACTUAL_VG_FULL,1);

size_ACTUAL_VG_FULL = size(ACTUAL_VG_FULL,1);

size_DAC_RESERVE_FULL = size(DAC_RESERVE_FULL,1);
size_RTC_RESERVE_FULL = size(RTC_RESERVE_FULL,1);
size_RTD_RESERVE_FULL = size(RTD_RESERVE_FULL,1);
