if lossesCheck > eps
    [RTC_BUS_DELIVERY_FACTORS_VAL,RTC_GEN_DELIVERY_FACTORS_VAL,RTC_LOAD_DELIVERY_FACTORS_VAL]=calculateDeliveryFactors(HRTC,nbus,ngen,GEN_VAL,BRANCHBUS_CALC_VAL,PTDF_VAL,repmat(initialLineFlows,1,HRTC),SYSTEMVALUE_VAL(mva_pu,1),BRANCHDATA_VAL(:,resistance),INJECTION_FACTOR.uels,GENBUS_VAL,BUS_VAL,INJECTION_FACTOR_VAL,LOAD_DIST_VAL,LOAD_DIST_STRING);    
else
    RTC_BUS_DELIVERY_FACTORS_VAL  = ones(nbus,HRTC);
    RTC_GEN_DELIVERY_FACTORS_VAL  = ones(ngen,HRTC);
    RTC_LOAD_DELIVERY_FACTORS_VAL = ones(size(LOAD_DIST_VAL,1),HRTC);
end
