disp('1 OPTIMAL');
disp('This means that the solution is optimal, that is, it is feasible (within tolerances');
disp('and it has been proven that no other feasible solution with better objective value');
disp('exists. Note, that the latter criterion is not influenced by the optcr and optca options.');
disp(' ');
disp('2 LOCALLY OPTIMAL');
disp('This message means that a local optimum has been found, that is, a solution that is');
disp('feasible (within tolerances) and it has been proven that there exists a neighborhood');
disp('of this solution in which no other feasible solution with better objective value exists.');
disp(' ');
disp('3 UNBOUNDED');
disp('This means that the solution is unbounded. This message is reliable if the problem is');
disp('linear, but occasionally it appears for dicult nonlinear problems that are not truly');
disp('unbounded, but that lack some strategically placed bounds to limit the variables');
disp('to sensible values.');
disp(' ');
disp('4 INFEASIBLE');
disp('This means that the problem has been proven to be infeasible. If this was not intended,');
disp('something is probably misspecified in the logic or the data.');
disp(' ');
disp('5 LOCALLY INFEASIBLE');
disp('This message means that no feasible point could be found for the problem from the given');
disp('starting point. It does not necessarily mean that no feasible point exists.');
disp(' ');
disp('6 INTERMEDIATE INFEASIBLE');
disp('This means that the current solution is not feasible, but that the solver stopped,');
disp('either because of a limit (e.g., iteration or resource), or because of some sort');
disp('of difficulty. Check the solver status for more information.');
disp(' ');
disp('7 INTERMEDIATE NONOPTIMAL');
disp('This is again an incomplete solution, but it appears to be feasible.');
disp(' ');
disp('8 INTEGER SOLUTION');
disp('A feasible solution has been found to a problem with discrete variables. There is more');
disp('detail following about whether this solution satisfies the termination criteria');
disp('(set by options optcr and optca).');
disp(' ');
disp('9 INTERMEDIATE NON-INTEGER');
disp('This is an incomplete solution to a problem with discrete variables. A feasible');
disp('solution has not yet been found.');
disp(' ');
disp('10 INTEGER INFEASIBLE');
disp('It has been proven that there is no feasible solution to a problem with discrete variables.');
disp(' ');
disp('11 LIC PROBLEM - NO SOLUTION');
disp('The solver cannot find the appropriate license key needed to use a specific subsolver.');
disp(' ');
disp('12 ERROR UNKNOWN');
disp('After a solver error, the model status is unknown.');
disp(' ');
disp('13 ERROR NO SOLUTI0N');
disp('An error occurred and no solution has been returned. No solution will be returned');
disp('to GAMS because of errors in the solution process.');
disp(' ');
disp('14 NO SOLUTION RETURNED');
disp('A solution is not expected for this solve. For example, the convert solver only');
disp('reformats the model but does not give a solution.');
disp(' ');
disp('15 SOLVED UNIQUE');
disp('This is used when a CNS model is solved and the solver somehow can be certain');
disp('that there is only one solution. The simplest examples are a linear model with');
disp('a non-singular Jacobian, a triangular model with constant non-zero elements');
disp('on the diagonal, and a triangular model where the functions are monotone in');
disp('the variable on the diagonal.');
disp(' ');
disp('16 SOLVED');
disp('Locally feasible in a CNS models - this is used when the model is feasible');
disp('and the Jacobian is non-singular and we do not know anything about uniqueness.');
disp(' ');
disp('17 SOLVED SINGULAR');
disp('Singular in a CNS models - this is used when the model is feasible (all constraints');
disp('are satisfied), but the Jacobian / Basis is singular. In this case there could be');
disp('other solutions as well, in the linear case a linear ray and in the nonlinear case some curve.');
disp(' ');
disp('18 UNBOUNDED - NO SOLUTION');
disp('The model is unbounded and no solution can be provided.');
disp(' ');
disp('19 INFEASIBLE - NO SOLUTION');
disp('The model is infeasible and no solution can be provided.');